language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
script:
  - cd tests; py.test --cov dnapy
install:
  - pip install --upgrade setuptools
  - pip uninstall -y pytest py
  - pip install -Iv codecov 
  - pip install -Iv pytest>=2.8
  - pip install -Iv pytest-cov 
  - pip install -Iv coverage 
  - pip install -Iv py>=1.4.29
  - pip install -Iv pysam
  - pip freeze
  - python setup.py install
after_success:
  - codecov
