language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
script:
  - cd tests; py.test --cov dnapy
before_install:
   - pip install pysam==0.8.4
   - pip freeze
install:
  - pip install codecov pytest pytest-cov coverage pysam
  - python setup.py install
after_success:
  - codecov
